CREATE TABLE  Locations (
    id INTEGER PRIMARY KEY,
    location_name TEXT
);

-- Insert the locations into the table
INSERT INTO Locations (location_name) VALUES 
('Abandoned Coffin'),
('Erdtree-Gazing Hill'),
('Altus Plateau'),
('Altus Highway Junction'),
('Forest-Spanning Greatbridge'),
('Bower of Bounty'),
('Windmill Village'),
('Windmill Heights'),
('Road of Iniquity Side Path'),
('Rampartside Path'),
('Shaded Castle Ramparts'),
('Shaded Castle Inner Gate'),
('Castellan''s Hall'),
('Unsightly Catacombs'),
('Sainted Hero''s Grave'),
('Sage''s Cave'),
('Perfumer''s Grotto'),
('Old Altus Tunnel'),
('Altus Tunnel'),
('Bridge of Iniquity'),
('First Mt. Gelmir Campsite'),
('Ninth Mt. Gelmir Campsite'),
('Road of Iniquity'),
('Seethewater River'),
('Seethewater Terminus'),
('Craftsman''s Shack'),
('Primeval Sorcerer Azur'),
('Wyndham Catacombs'),
('Gelmir Hero''s Grave'),
('Seethewater Cave'),
('Volcano Cave'),
('Outer Wall Phantom Tree'),
('Minor Erdtree Church'),
('Outer Wall Battleground'),
('Hermit Merchant''s Shack'),
('Capital Rampart'),
('Auriza Side Tomb'),
('Auriza Hero''s Grave'),
('Sealed Tunnel'),
('Divine Tower of West Altus: Gate'),
('Divine Tower of West Altus');