CREATE TABLE  Locations (
    id INTEGER PRIMARY KEY,
    location_name TEXT
);

-- Insert the locations into the table
INSERT INTO Locations (location_name) VALUES 
('Church of Elleh'),
('Gatefront'),
('Waypoint Ruins Cellar'),
('Artist''s Shack'),
('Third Church of Marika'),
('Fort Haight West'),
('Agheel Lake South'),
('Agheel Lake North'),
('Church of Dragon Communion'),
('Seaside Ruins'),
('Mistwood Outskirts'),
('Murkwater Coast'),
('Summonwater Village Outskirts'),
('Stormfoot Catacombs'),
('Murkwater Catacombs'),
('Groveside Cave'),
('Coastal Cave'),
('Murkwater Cave'),
('Highroad Cave'),
('Limgrave Tunnels'),
('Cave of Knowledge'),
('Stranded Graveyard'),
('Stormhill Shack'),
('Castleward Tunnel'),
('Margit, the Fell Omen'),
('Warmaster''s Shack'),
('Saintsbridge'),
('Deathtouched Catacombs'),
('Limgrave Tower Bridge'),
('Divine Tower of Limgrave'),
('Church of Pilgrimage'),
('Castle Morne Rampart'),
('Tombsward'),
('South of the Lookout Tower'),
('Ailing Village Outskirts'),
('Beside The Crater-Pocked Glade'),
('Isolated Merchant''s Shack'),
('Fourth Church of Marika'),
('Bridge of Sacrifice'),
('Castle Morne Lift'),
('Behind The Castle'),
('Beside the Rampart Gaol'),
('Morne Moangrave'),
('Impaler''s Catacombs'),
('Tombsward Catacombs'),
('Earthbore Cave'),
('Tombsward Cave'),
('Morne Tunnel'),
('Stormveil Main Gate'),
('Gateside Chamber'),
('Stormveil Cliffside'),
('Rampart Tower'),
('Liftside Chamber'),
('Secluded Cell'),
('Godrick the Grafted');