CREATE TABLE  Locations (
    id INTEGER PRIMARY KEY,
    location_name TEXT
);

-- Insert the locations into the table
INSERT INTO Locations (location_name) VALUES 
('Lake-Facing Cliffs'),
('Liurnia Lake Shore'),
('Laskyar Ruins'),
('Scenic Isle'),
('Academy Gate Town'),
('South Raya Lucaria Gate'),
('Main Academy Gate'),
('Liurnia Highway South'),
('Liurnia Highway North'),
('Gate Town Bridge'),
('Artist''s Shack'),
('Eastern Liurnia Lake Shore'),
('Jarburg'),
('Ranni''s Chamber'),
('Eastern Tableland'),
('Church of Vows'),
('Ruined Labyrinth'),
('Mausoleum Compound'),
('Slumbering Wolf''s Shack'),
('Boilprawn Shack'),
('Fallen Ruins of the Lake'),
('Folly on the Lake'),
('Village of the Albinaurics'),
('Converted Tower'),
('Revenger''s Shack'),
('Temple Quarter'),
('Crystalline Woods'),
('Foot of the Four Belfries'),
('The Four Belfries'),
('Sorcerer''s Isle'),
('East Gate Bridge Trestle'),
('Gate Town North'),
('Northern Liurnia Lake Shore'),
('Road to the Manor'),
('Main Caria Manor Gate'),
('Manor Upper Level'),
('Manor Lower Level'),
('Royal Moongazing Grounds'),
('Ranni''s Rise'),
('Behind Caria Manor'),
('The Ravine'),
('Ravine-Veiled Village'),
('Cliffbottom Catacombs'),
('Road''s End Catacombs'),
('Black Knife Catacombs'),
('Stillwater Cave'),
('Lakeside Crystal Cave'),
('Academy Crystal Cave'),
('Raya Lucaria Crystal Tunnel'),
('Study Hall Entrance'),
('Liurnia Tower Bridge'),
('Divine Tower of Liurnia'),
('East Raya Lucaria Gate'),
('Bellum Church'),
('Grand Lift of Dectus'),
('Frenzied Flame Village Outskirts'),
('Church of Inhibition'),
('Ruin-Strewn Precipice'),
('Ruin-Strewn Precipice Overlook'),
('Magma Wyrm Makar'),
('Moonlight Altar'),
('Cathedral of Manus Celes'),
('Altar South');